complexity:
  LongMethod:
    active: true
    threshold: 300
  CyclomaticComplexMethod:
    active: true
    threshold: 40
  LongParameterList:
    active: false
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInObjects: 20
    thresholdInInterfaces: 20
    thresholdInEnums: 20
    thresholdInFiles: 20

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false

style:
  NewLineAtEndOfFile:
    active: false
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    active: false
  UnusedPrivateProperty:
    active: false
  ReturnCount:
    active: false
